name: Backend CI/CD

on:
  pull_request:
    paths:
      - 'backend/'
      - '.github/workflows/backend.yml'
  push:
    branches:
      - 'main'
    paths:
      - 'backend/'
      - '.github/workflows/backend.yml'

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        working-directory: backend # <--- This tells the runner to change into the backend directory
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt # Now this path works!
          pip install ruff mypy pytest
      - name: Lint
        working-directory: backend
        run: ruff check . --output-format=github
      - name: Type check
        working-directory: backend # <--- And here
        run: mypy . || true
      - name: Tests
        working-directory: backend # <--- And here
        run: pytest -q app/tests || true