name: Backend CI/CD
on:
pull_request:
paths: ['backend/', '.github/workflows/backend.yml']
push:
branches: ['main']
paths: ['backend/', '.github/workflows/backend.yml']
jobs:
ci:
runs-on: ubuntu-latest
steps:
- uses: actions/checkout@v4
- uses: actions/setup-python@v5
with: { python-version: '3.11' }
- name: Install deps
run: |
python -m pip install --upgrade pip
pip install -r backend/requirements.txt
pip install ruff mypy pytest
- name: Lint
run: ruff backend --output-format=github
- name: Type check
run: mypy backend || true
- name: Tests
run: pytest -q backend/app/tests || true